POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
    "name": "My Product",
    "price": 100
}

###
GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njk1MTcyNTYsInN1YiI6IjY2ZTgzMDM0LTBiM2YtNGViYi1iZGZkLTdlYzQ5YzJmODE5OSJ9.hKlphPP6_Ex6Kx5dK99isGwrc9wmYo87cxIOS4tI4QA

###
GET http://localhost:8000/products/0be84bc2-df9c-4c88-a9ae-aafc009bebd6 HTTP/1.1

###
PUT http://localhost:8000/products/0be84bc2-df9c-4c88-a9ae-aafc009bebd6 HTTP/1.1
Content-Type: application/json

{
    "name": "My Product Updated",
    "price": 150
}

###
DELETE http://localhost:8000/products/0be84bc2-df9c-4c88-a9ae-aafc009bebd6 HTTP/1.1